# Generated by Django 4.0.5 on 2022-07-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
